### ISSUE TITLE
Google+ OAuth requests

### ISSUE THREAD

**Issue by ibecir** [thephpleague/oauth2-google#74] opened 2019-01-30 08:56 UTC
After updating the library to the newest version (3.0) we got an email from Google saying that application is still sending deprecated Google+ OAuth requests. Email is shown below. Can you please instruct what to do? Thanks in advance

The email below contains your most recent usage of Google+ APIs. Note: It includes Google+ OAuth scope requests, which are also affected by the Google+ shutdown. A prior email sent to active API callers did not include information about OAuth requests. One final reminder email will be sent in February to users who still have active API or OAuth request activity.

**Comment by shadowhand** [comment] 2019-01-30 14:47
Are you making any calls besides authentication? Any custom configuration of the GoogleProvider?

**Comment by MarGul** [comment] 2019-01-31 07:43
We got the same email but also got a correction email sent out today. Apparently it's only the projects that are directly requesting `https://www.googleapis.com/plus/v1/people/me` that should be affected. I have looked through the code and can't see any calls to that specifically. It is requesting the `profile` scope but I think that's not the same.

Is the project calling the `plus.me` scope or the `https://www.googleapis.com/plus/v1/people/me` endpoint for getting user information?

**Comment by ibecir** [comment] 2019-01-31 08:14
We got the correction email as well, and no, we are not using any custom calls accept those given by library. We are also not getting data from `https://www.googleapis.com/plus/v1/people/me` or `plus.me` scope.

**Comment by mxdpeep** [comment] 2019-01-31 15:59
there's no Google+ usage in the 3.x client whatsover

*Filip Oščádal*
*https://fredbrooker.gscloud.cz/cs <https://fredbrooker.gscloud.cz/cs>*

**Comment by wacki4** [comment] 2019-02-04 09:03
I've repaired it - by installing first newest league/oauth2-client, and after that reinstalling league/oauth2-google. Now everything looks great, and works without any problem.

**Comment by mxdpeep** [comment] 2019-02-05 22:14
so the problem was caused by old installations, not current version of the package * please, close this issue

**Closed** 2019-02-06 05:49 UTC
Labels: question

**Comment by pattmeterson** [comment] 2019-02-11 22:55
Which API Library in the API Console should be enabled if the Google+ API is no longer to be used?

**Comment by shadowhand** [comment] 2019-02-12 02:40
[OpenID Connect - Google Identity Platform](https://developers.google.com/identity/protocols/OpenIDConnect)

**Comment by pattmeterson** [comment] 2019-02-12 02:47
Yes, I tried searching for that but no results are found. I am searching for it on this page : https://console.developers.google.com/apis/library

Currently, I have the Google+ API enabled and after reading through a few different pages, I can't seem to find which API I need to enable to move forward.

Thanks for the quick response :)

**Comment by shadowhand** [comment] 2019-02-12 02:50
You don't need to have specific APIs enabled, but it is recommended to have the [People API][1] enabled for best reliability when fetching user details.

[1]: https://console.developers.google.com/apis/library/people.googleapis.com

**Comment by pattmeterson** [comment] 2019-02-12 02:58
Ahh, I see. I had enabled the People API after reading one of the articles pertaining to this update but hadn't seen a lot of direction on what to do with it once it was enabled. I will make the update to the latest version of oauth2-google within my app and remove the Google+ API from the console.

Thanks for your help!
